[package]
name = "dynamic_graph_vertex_add_component_sum"
version = "0.1.0"
edition = "2024"

[dependencies]
fast-io = { path = "../../../../macro/fast-io" }
offline-dynamic-connectivity = { path = "../../../../graph/offline-dynamic-connectivity" }
union-find-with-rollback-abstract = { path = "../../../../data-structure/union-find/union-find-with-rollback-abstract" }
