[workspace]
resolver = "3"
members = [
    "data-structure/balanced-binary-search-tree/implicit-treap",
    "data-structure/balanced-binary-search-tree/treap",
    "data-structure/balanced-binary-search-tree/treap-map",
    "data-structure/doubling",
    "data-structure/fenwick-tree",
    "data-structure/fenwick-tree-abstract",
    "data-structure/interval-set",
    "data-structure/mo",
    "data-structure/mo-with-rollback",
    "data-structure/partially-persistent-array",
    "data-structure/persistent-array",
    "data-structure/persistent-stack",
    "data-structure/range-mode-query",
    "data-structure/segment-tree/dual-segment-tree",
    "data-structure/segment-tree/dynamic-segment-tree",
    "data-structure/segment-tree/lazy-segment-tree",
    "data-structure/segment-tree/persistent-segment-tree",
    "data-structure/segment-tree/persistent-segment-tree-pool",
    "data-structure/segment-tree/segment-tree",
    "data-structure/segment-tree/segment-tree-recursive",
    "data-structure/succinct-indexable-dictionary",
    "data-structure/trie/binary-trie",
    "data-structure/trie/trie",
    "data-structure/trie/x-fast-trie",
    "data-structure/trie/y-fast-trie",
    "data-structure/union-find/bipartite-union-find",
    "data-structure/union-find/partially-persistent-union-find",
    "data-structure/union-find/persistent-union-find",
    "data-structure/union-find/range-parallel-union-find",
    "data-structure/union-find/union-find",
    "data-structure/union-find/union-find-abstract",
    "data-structure/union-find/union-find-with-potential",
    "data-structure/union-find/union-find-with-rollback",
    "data-structure/union-find/union-find-with-rollback-abstract",
    "data-structure/wavelet-matrix",
    "graph/bellman-ford",
    "graph/biconnected-components",
    "graph/block-cut-tree",
    "graph/compressed-sparse-row",
    "graph/dijkstra",
    "graph/ford-fulkerson",
    "graph/hopcroft-karp",
    "graph/kruskal",
    "graph/low-link",
    "graph/maxflow",
    "graph/mincostflow",
    "graph/offline-dynamic-connectivity",
    "graph/strongly-connected-components-kosaraju",
    "graph/strongly-connected-components-tarjan",
    "graph/topological-sort",
    "graph/two-edge-connected-components",
    "graph/two-sat",
    "graph/warshall-floyd",
    "heuristic/simulated_annealing",
    "heuristic/time-keeper",
    "macro/chmax",
    "macro/chmin",
    "macro/debug",
    "macro/fast-io",
    "macro/itertools",
    "macro/lower-bound",
    "macro/query",
    "macro/upper-bound",
    "math/and-convolution",
    "math/bell-number",
    "math/binomial",
    "math/crt",
    "math/divisor-zeta-mobius",
    "math/eratosthenes",
    "math/eratosthenes-factorization",
    "math/eratosthenes-segment",
    "math/ext-gcd",
    "math/floor-sum",
    "math/garner",
    "math/gcd-convolution",
    "math/lcm-convolution",
    "math/linear-sieve",
    "math/miller-rabin",
    "math/modint/dynamic-modint",
    "math/modint/dynamic-montgomery-modint",
    "math/modint/modint",
    "math/modint/modint-mersenne61",
    "math/modint/montgomery-modint",
    "math/modint/montgomery-modint-64",
    "math/numeric-traits",
    "math/or-convolution",
    "math/partition-number",
    "math/pollard-rho",
    "math/primitive-root",
    "math/stirling-number-second",
    "math/subset-convolution",
    "math/walsh-hadamard",
    "math/xor-convolution",
    "math/xorshift-128",
    "math/xorshift-64",
    "math/zeta-mobius",
    "sequence/longest-increasing-subsequence",
    "string/aho-corasick",
    "string/kmp",
    "string/lcp-array",
    "string/longest-common-substring",
    "string/manacher",
    "string/rolling-hash",
    "string/run-length",
    "string/suffix-array",
    "string/z-algorithm",
    "string/z-algorithm-online",
    "tree/ahu",
    "tree/cartesian-tree",
    "tree/centroid",
    "tree/centroid-decomposition",
    "tree/euler-tour",
    "tree/heavy-light-decomposition",
    "tree/level-ancestor",
    "tree/level-ancestor-offline",
    "tree/rerooting",
    "tree/tree-isomorphism",
    "tree/tree-isomorphism-rerooting",
    "verification/aizu-online-judge/alds1/alds1_11_d",
    "verification/aizu-online-judge/alds1/alds1_12_a",
    "verification/aizu-online-judge/alds1/alds1_12_b",
    "verification/aizu-online-judge/alds1/alds1_12_c",
    "verification/aizu-online-judge/alds1/alds1_14_a_kmp",
    "verification/aizu-online-judge/alds1/alds1_14_a_rolling_hash",
    "verification/aizu-online-judge/alds1/alds1_14_b_kmp",
    "verification/aizu-online-judge/alds1/alds1_14_b_rolling_hash",
    "verification/aizu-online-judge/alds1/alds1_14_d",
    "verification/aizu-online-judge/alds1/alds1_5_d",
    "verification/aizu-online-judge/dpl/dpl_1_d",
    "verification/aizu-online-judge/dpl/dpl_5_a",
    "verification/aizu-online-judge/dpl/dpl_5_a_montgomery",
    "verification/aizu-online-judge/dpl/dpl_5_a_montgomery_64",
    "verification/aizu-online-judge/dpl/dpl_5_b",
    "verification/aizu-online-judge/dpl/dpl_5_b_montgomery",
    "verification/aizu-online-judge/dpl/dpl_5_b_montgomery_64",
    "verification/aizu-online-judge/dpl/dpl_5_c",
    "verification/aizu-online-judge/dpl/dpl_5_d",
    "verification/aizu-online-judge/dpl/dpl_5_e",
    "verification/aizu-online-judge/dpl/dpl_5_f",
    "verification/aizu-online-judge/dpl/dpl_5_g",
    "verification/aizu-online-judge/dpl/dpl_5_h",
    "verification/aizu-online-judge/dpl/dpl_5_i",
    "verification/aizu-online-judge/dpl/dpl_5_j",
    "verification/aizu-online-judge/dpl/dpl_5_k",
    "verification/aizu-online-judge/dpl/dpl_5_l",
    "verification/aizu-online-judge/dsl/dsl_1_a",
    "verification/aizu-online-judge/dsl/dsl_1_b",
    "verification/aizu-online-judge/dsl/dsl_2_a",
    "verification/aizu-online-judge/dsl/dsl_2_b",
    "verification/aizu-online-judge/dsl/dsl_2_d_dual_segtree",
    "verification/aizu-online-judge/dsl/dsl_2_d_lazy_segtree",
    "verification/aizu-online-judge/dsl/dsl_2_e_dual_segtree",
    "verification/aizu-online-judge/dsl/dsl_2_e_lazy_segtree",
    "verification/aizu-online-judge/dsl/dsl_2_f",
    "verification/aizu-online-judge/dsl/dsl_2_g_lazy_segtree",
    "verification/aizu-online-judge/dsl/dsl_2_g_segtree",
    "verification/aizu-online-judge/dsl/dsl_2_h_lazy_segtree",
    "verification/aizu-online-judge/dsl/dsl_2_h_segtree",
    "verification/aizu-online-judge/dsl/dsl_2_i",
    "verification/aizu-online-judge/grl/grl_1_a",
    "verification/aizu-online-judge/grl/grl_1_b",
    "verification/aizu-online-judge/grl/grl_1_c",
    "verification/aizu-online-judge/grl/grl_2_a",
    "verification/aizu-online-judge/grl/grl_3_a",
    "verification/aizu-online-judge/grl/grl_3_b",
    "verification/aizu-online-judge/grl/grl_3_c_kosaraju",
    "verification/aizu-online-judge/grl/grl_3_c_tarjan",
    "verification/aizu-online-judge/grl/grl_4_a",
    "verification/aizu-online-judge/grl/grl_4_b",
    "verification/aizu-online-judge/grl/grl_5_a",
    "verification/aizu-online-judge/grl/grl_5_b",
    "verification/aizu-online-judge/grl/grl_5_c",
    "verification/aizu-online-judge/grl/grl_5_d",
    "verification/aizu-online-judge/grl/grl_5_e",
    "verification/aizu-online-judge/grl/grl_6_a",
    "verification/aizu-online-judge/grl/grl_6_b",
    "verification/aizu-online-judge/grl/grl_7_a_ford_fulkerson",
    "verification/aizu-online-judge/grl/grl_7_a_maxflow",
    "verification/aizu-online-judge/itp2/itp2_6_c",
    "verification/aizu-online-judge/itp2/itp2_6_d",
    "verification/aizu-online-judge/itp2/itp2_7_a",
    "verification/aizu-online-judge/itp2/itp2_7_b",
    "verification/aizu-online-judge/itp2/itp2_7_c",
    "verification/aizu-online-judge/itp2/itp2_7_d",
    "verification/aizu-online-judge/itp2/itp2_8_a",
    "verification/aizu-online-judge/itp2/itp2_8_b",
    "verification/aizu-online-judge/itp2/itp2_8_c",
    "verification/aizu-online-judge/itp2/itp2_8_d",
    "verification/aizu-online-judge/itp2/itp2_9_a",
    "verification/aizu-online-judge/ntl/ntl_1_a_eratosthenes",
    "verification/aizu-online-judge/ntl/ntl_1_a_linear_sieve",
    "verification/aizu-online-judge/ntl/ntl_1_b",
    "verification/aizu-online-judge/ntl/ntl_1_d_eratosthenes",
    "verification/aizu-online-judge/ntl/ntl_1_d_linear_sieve",
    "verification/aizu-online-judge/ntl/ntl_1_e",
    "verification/aizu-online-judge/volume/volume01-0157",
    "verification/aizu-online-judge/volume/volume15-1508",
    "verification/aizu-online-judge/volume/volume15-1549",
    "verification/aizu-online-judge/volume/volume15-1595",
    "verification/aizu-online-judge/volume/volume16-1613",
    "verification/aizu-online-judge/volume/volume28-2880",
    "verification/aizu-online-judge/volume/volume30-3022",
    "verification/aizu-online-judge/volume/volume5-0555",
    "verification/library-checker/convolution/bitwise_and_convolution",
    "verification/library-checker/convolution/bitwise_or_convolution",
    "verification/library-checker/convolution/bitwise_xor_convolution",
    "verification/library-checker/convolution/gcd_convolution",
    "verification/library-checker/convolution/lcm_convolution",
    "verification/library-checker/data_structure/associative_array",
    "verification/library-checker/data_structure/double_ended_priority_queue_treap",
    "verification/library-checker/data_structure/dynamic_sequence_range_affine_range_sum_implicit_treap",
    "verification/library-checker/data_structure/ordered_set",
    "verification/library-checker/data_structure/ordered_set_treap",
    "verification/library-checker/data_structure/persistent_unionfind_persistent",
    "verification/library-checker/data_structure/persistent_unionfind_rollback",
    "verification/library-checker/data_structure/point_add_range_sum",
    "verification/library-checker/data_structure/point_add_range_sum_abstract",
    "verification/library-checker/data_structure/point_set_range_composite",
    "verification/library-checker/data_structure/point_set_range_frequency",
    "verification/library-checker/data_structure/predecessor_problem/dynamic-segment-tree",
    "verification/library-checker/data_structure/predecessor_problem/fenwick-tree",
    "verification/library-checker/data_structure/predecessor_problem/implicit-treap",
    "verification/library-checker/data_structure/predecessor_problem/lazy-segment-tree",
    "verification/library-checker/data_structure/predecessor_problem/persistent-segment-tree",
    "verification/library-checker/data_structure/predecessor_problem/persistent-segment-tree-pool",
    "verification/library-checker/data_structure/predecessor_problem/segment-tree",
    "verification/library-checker/data_structure/predecessor_problem/treap",
    "verification/library-checker/data_structure/predecessor_problem/x-fast-trie",
    "verification/library-checker/data_structure/predecessor_problem/y-fast-trie",
    "verification/library-checker/data_structure/range_add_range_min",
    "verification/library-checker/data_structure/range_affine_point_get-lazy-segment-tree",
    "verification/library-checker/data_structure/range_affine_range_sum",
    "verification/library-checker/data_structure/range_kth_smallest",
    "verification/library-checker/data_structure/range_kth_smallest_pool",
    "verification/library-checker/data_structure/range_kth_smallest_wavelet_matrix",
    "verification/library-checker/data_structure/range_parallel_unionfind",
    "verification/library-checker/data_structure/range_reverse_range_sum_implicit_treap",
    "verification/library-checker/data_structure/range_set_range_composite",
    "verification/library-checker/data_structure/range_set_range_composite_intervalset",
    "verification/library-checker/data_structure/rectangle_sum",
    "verification/library-checker/data_structure/set_xor_min",
    "verification/library-checker/data_structure/static_range_count_distinct",
    "verification/library-checker/data_structure/static_range_frequency",
    "verification/library-checker/data_structure/static_range_frequency_persistent_segtree",
    "verification/library-checker/data_structure/static_range_frequency_wavelet_matrix",
    "verification/library-checker/data_structure/static_range_inversions_query",
    "verification/library-checker/data_structure/static_range_mode_query",
    "verification/library-checker/data_structure/static_range_mode_query_mo",
    "verification/library-checker/data_structure/static_range_mode_query_mo_with_rollback",
    "verification/library-checker/data_structure/static_range_sum-fenwick-tree",
    "verification/library-checker/data_structure/static_range_sum_with_upper_bound_wavelet_matrix",
    "verification/library-checker/data_structure/staticrmq-segment-tree",
    "verification/library-checker/data_structure/unionfind",
    "verification/library-checker/data_structure/unionfind_with_potential",
    "verification/library-checker/data_structure/unionfind_with_potential_non_commutative_group",
    "verification/library-checker/enumerative_combinatorics/binomial_coefficient_prime_mod",
    "verification/library-checker/enumerative_combinatorics/binomial_coefficient_prime_mod_montgomery",
    "verification/library-checker/enumerative_combinatorics/number_of_subsequences",
    "verification/library-checker/graph/biconnected_components",
    "verification/library-checker/graph/bipartitematching",
    "verification/library-checker/graph/bipartitematching_maxflow",
    "verification/library-checker/graph/dynamic_graph_vertex_add_component_sum",
    "verification/library-checker/graph/minimum_spanning_tree",
    "verification/library-checker/graph/scc_kosaraju",
    "verification/library-checker/graph/scc_tarjan",
    "verification/library-checker/graph/shortest_path",
    "verification/library-checker/graph/two_edge_connected_components",
    "verification/library-checker/number_theory/enumerate_primes-eratosthenes",
    "verification/library-checker/number_theory/enumerate_primes-eratosthenes-segment",
    "verification/library-checker/number_theory/factorize",
    "verification/library-checker/number_theory/primality_test",
    "verification/library-checker/number_theory/primitive_root",
    "verification/library-checker/number_theory/sum_of_floor_of_linear",
    "verification/library-checker/other/two_sat",
    "verification/library-checker/sample/aplusb",
    "verification/library-checker/sample/many_aplusb",
    "verification/library-checker/sample/many_aplusb_128bit",
    "verification/library-checker/set_power_series/subset_convolution",
    "verification/library-checker/string/aho_corasick",
    "verification/library-checker/string/enumerate_palindromes",
    "verification/library-checker/string/longest_common_substring",
    "verification/library-checker/string/number_of_substrings",
    "verification/library-checker/string/suffixarray",
    "verification/library-checker/string/zalgorithm",
    "verification/library-checker/string/zalgorithm_online",
    "verification/library-checker/tree/cartesian_tree",
    "verification/library-checker/tree/jump_on_tree",
    "verification/library-checker/tree/jump_on_tree_doubling",
    "verification/library-checker/tree/jump_on_tree_la",
    "verification/library-checker/tree/jump_on_tree_la_offline",
    "verification/library-checker/tree/lca",
    "verification/library-checker/tree/lca_doubling",
    "verification/library-checker/tree/rooted_tree_isomorphism_classification",
    "verification/library-checker/tree/tree_diameter-rerooting",
    "verification/library-checker/tree/tree_path_composite_sum",
    "verification/library-checker/tree/vertex_add_path_sum",
    "verification/library-checker/tree/vertex_add_subtree_sum",
    "verification/library-checker/tree/vertex_set_path_composite",
]
exclude = [
    "verification/atcoder",
    "verification/codeforces",
]
