[package]
name = "binomial_coefficient_prime_mod_montgomery"
version = "0.1.0"
edition = "2024"

[dependencies]
binomial = { path = "../../../../math/binomial" }
dynamic-modint = { path = "../../../../math/modint/dynamic-modint" }
dynamic-montgomery-modint = { path = "../../../../math/modint/dynamic-montgomery-modint" }
fast-io = { path = "../../../../macro/fast-io" }
