[package]
name = "vertex_set_path_composite"
version = "0.1.0"
edition = "2024"

[dependencies]
euler-tour = { path = "../../../../tree/euler-tour" }
fast-io = { path = "../../../../macro/fast-io" }
modint = { path = "../../../../math/modint/modint" }
segment-tree = { path = "../../../../data-structure/segment-tree/segment-tree" }
